version: "3.8"

services:
    trade-journal:
        build:
            context: .
            dockerfile: Dockerfile
        image: trade-journal:latest
        container_name: trade-journal
        ports:
            - "3002:4000" # Exposes app on port 3002
        restart: unless-stopped
        environment:
            - PORT=4000
            - DATA_DIR=/data
            - NODE_ENV=production
        volumes:
            - trade-journal-data:/data
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:4000/api/ping",
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s

volumes:
    trade-journal-data:
        driver: local
