
version: '3'

services:
  trade-journal:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-trade-journal:latest}
    container_name: trade-journal
    ports:
      - "${HOST_PORT:-8080}:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
      - DATA_DIR=/data
      - NODE_ENV=production
    volumes:
      - trade-journal-data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  trade-journal-data:
    driver: local

