
version: '3'

services:
  trade-journal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
      - DATA_DIR=/data
    volumes:
      - trade-journal-data:/data

volumes:
  trade-journal-data:
    driver: local
