
version: '3'

services:
  trade-journal:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
      - DATA_DIR=/data
      - NODE_ENV=development
    volumes:
      - trade-journal-data:/data
      - ./:/app
      - /app/node_modules

volumes:
  trade-journal-data:
    driver: local
