import { Trade } from '@/types';
import { saveTrades } from './storageCore';

// Function to add dummy trades to localStorage
export const addDummyTrades = (): void => {
  const today = new Date();
  const demoTrades = [
    {
      id: "demo-1",
      symbol: "AAPL",
      type: "stock", // Changed from 'equity' to 'stock'
      direction: "long",
      quantity: 100,
      entryDate: new Date(today.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      entryPrice: 185.25,
      exitDate: new Date(today.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      exitPrice: 192.53,
      status: "closed",
      stopLoss: 180.00,
      takeProfit: 195.00,
      fees: 2.95,
      strategy: "Breakout",
      notes: "Earnings beat expectations, strong uptrend formed.",
      grade: "A",
      images: [],
      tags: ["tech", "long-term"],
    },
    {
      id: "demo-2",
      symbol: "MSFT",
      type: "stock", // Changed from 'equity' to 'stock'
      direction: "long",
      quantity: 50,
      entryDate: new Date(today.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      entryPrice: 380.45,
      status: "open",
      stopLoss: 370.00,
      takeProfit: 400.00,
      fees: 1.99,
      strategy: "Trend Following",
      notes: "Following uptrend, waiting for cloud services news catalyst.",
      grade: "B",
      images: [],
      tags: ["tech", "cloud"],
    },
    {
      id: "demo-3",
      symbol: "TSLA",
      type: "stock", // Changed from 'equity' to 'stock'
      direction: "short",
      quantity: 25,
      entryDate: new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      entryPrice: 785.50,
      exitDate: new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      exitPrice: 760.00,
      status: "closed",
      stopLoss: 800.00,
      takeProfit: 750.00,
      fees: 0.99,
      strategy: "Mean Reversion",
      notes: "Overbought conditions, expecting pullback.",
      grade: "C",
      images: [],
      tags: ["auto", "overvalued"],
    },
    {
      id: "demo-4",
      symbol: "ES",
      type: "futures",
      direction: "long",
      quantity: 2,
      entryDate: new Date(today.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      entryPrice: 4520.25,
      exitDate: new Date(today.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      exitPrice: 4535.50,
      status: "closed",
      stopLoss: 4510.00,
      takeProfit: 4540.00,
      fees: 2.50,
      strategy: "Scalping",
      notes: "Quick profit from overnight session.",
      grade: "B",
      images: [],
      tags: ["index", "overnight"],
      contractDetails: {
        exchange: "CME",
        tickSize: 0.25,
        contractSize: 50,
        tickValue: 12.50
      }
    },
    {
      id: "demo-5",
      symbol: "GC",
      type: "futures",
      direction: "long",
      quantity: 1,
      entryDate: new Date(today.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      entryPrice: 1950.50,
      status: "open",
      stopLoss: 1940.00,
      takeProfit: 1970.00,
      fees: 3.00,
      strategy: "Trend Following",
      notes: "Gold prices rising due to inflation fears.",
      grade: "A",
      images: [],
      tags: ["gold", "inflation"],
      contractDetails: {
        exchange: "COMEX",
        tickSize: 0.1,
        contractSize: 100,
        tickValue: 10
      }
    },
    {
      id: "demo-6",
      symbol: "EURUSD",
      type: "forex",
      direction: "short",
      quantity: 10000,
      entryDate: new Date(today.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      entryPrice: 1.1050,
      exitDate: new Date(today.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      exitPrice: 1.1025,
      status: "closed",
      stopLoss: 1.1075,
      takeProfit: 1.1000,
      fees: 0.00,
      strategy: "News Event",
      notes: "ECB rate decision caused Euro to weaken.",
      grade: "B",
      images: [],
      tags: ["currency", "ECB"],
    },
    {
      id: "demo-7",
      symbol: "BTCUSD",
      type: "crypto",
      direction: "long",
      quantity: 0.5,
      entryDate: new Date(today.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      entryPrice: 45000,
      status: "open",
      stopLoss: 44000,
      takeProfit: 47000,
      fees: 15.00,
      strategy: "Hodl",
      notes: "Long-term investment in Bitcoin.",
      grade: "B",
      images: [],
      tags: ["crypto", "long-term"],
    },
    {
      id: "demo-8",
      symbol: "SPY",
      type: "options",
      direction: "long",
      quantity: 5,
      entryDate: new Date(today.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      entryPrice: 450.00,
      exitDate: new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      exitPrice: 455.00,
      status: "closed",
      stopLoss: 445.00,
      takeProfit: 460.00,
      fees: 1.50,
      strategy: "Covered Call",
      notes: "Collecting premium on SPY holdings.",
      grade: "C",
      images: [],
      tags: ["options", "income"],
    }
  ];

  saveTrades(demoTrades as Trade[]);
};
